# /**/move_group:
#   ros__parameters:

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    # - gripper_controller

  joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      # - $(var tf_prefix)joint_5
      # - $(var tf_prefix)joint_6

  # gripper_controller:
  #   action_ns: gripper_cmd
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - $(var tf_prefix)gripper_jaw1_joint
